# These are supported funding model platforms

github: []
patreon: # Username
open_collective: # Username
ko_fi: "BuriedInCode"
tidelift: # Platform Name / Project Name
community_bridge: # Project Name
liberapay: # Username
issuehunt: # Username
otechie: # Username
custom: []